version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://user:password@db/mydb
    depends_on:
      - db
    volumes:
      - .:/app
    

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:  
    build: ./nginx  
    ports:
      - "80:80"  
    depends_on:
      - web

volumes:
  postgres_data: